### ISSUE TITLE
Update to newer cake core please!

### ISSUE THREAD

**Issue by jessejacob** [cake-contrib/Cake.DotNetCoreEf#27]
Tried updating my pinned version of cake from 0.21.1 to 0.22.0 and now I get:

Error: The assembly 'Cake.DotNetCoreEf, Version=0.4.0.0, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.17.0).
This assembly need to reference at least Cake.Core version 0.22.0.
Another option is to downgrade Cake to an earlier version.
It's not recommended, but you can explicitly opt-out of assembly verification
by configuring the Skip Verification setting to true
(i.e. command line parameter "--settings_skipverification=true",
envrionment variable "CAKE_SETTINGS_SKIPVERIFICATION=true",
read more about configuration at https://cakebuild.net/docs/fundamentals/configuration)

I tried using the unpublished nuget from the 0.5.0 release, but it shows the same message. It looks like from closed issues it's been about a year since someone asked for a cake core update...any chance this could happen soon?

**Comment by mvanput** [comment]
I will update the package to the latest version

**Comment by liri2006** [comment]
+1

**Comment by mvanput** [comment]
@jessejacob @liri2006 fixed in 0.6.0. This version is published on NuGet. Can you check if it works?

**Comment by liri2006** [comment]
@mvput, works great. Thank you for the update!

**Comment by jessejacob** [comment]
Thanks!
