### ISSUE TITLE
Suggest different signatures for 'dotnet ef' CLI interaction

### ISSUE THREAD

**Issue by dandrejvv** [cake-contrib/Cake.DotNetCoreEf#33]
The current way that the tool have aliases setup are very confusing to know how to use (apart from the lack of documentation). May I suggest a relook at how to allow a user to specify the `project containing the DbContext`, the `DbContext type name` name as well as the `startup project`, etc?

P.S. I'm happy to contribute.

**Comment by mvanput** [comment]
@dandrejvv feel free to share your ideas about it and create a PR
