### ISSUE TITLE
Release 0.7.0 not published to nuget.org

### ISSUE THREAD

**Issue by rucker** [cake-contrib/Cake.DotNetCoreEf#34]
The most recent version available on nuget.org is 0.6.0 and I would like to consume the latest NuGet package. Could someone please publish v0.7.0 to nuget.org?

**Comment by mvanput** [comment]
@rucker I will take a look at it.

**Comment by rucker** [comment]
@mvput Anything on this?

**Comment by mvanput** [comment]
@rucker the 0.8.0 should be available on nuget.
