### ISSUE TITLE
Is there a way to run migrations script without building the project?

### ISSUE THREAD

**Issue by x2764tech** [cake-contrib/Cake.DotNetCoreEf#39]
Want to run `dotnet ef migrations script --no-build ....`, but can't find option to do this

**Comment by x2764tech** [comment]
[`DotNetCorePublishSettings`][DotNetCorePublishSettings] has a [`NoBuild`][NoBuild], and this project should mirror that.

[DotNetCorePublishSettings]: https://cakebuild.net/api/Cake.Common.Tools.DotNetCore.Publish/DotNetCorePublishSettings/
[NoBuild]: https://cakebuild.net/api/Cake.Common.Tools.DotNetCore.Publish/DotNetCorePublishSettings/1D3333F2

**Comment by mvanput** [comment]
I've released this in the 0.9.0. Thanks for your contribution @x2764tech !

**Comment by chimepalden** [comment]
@mvput So, after no-build migration, before updating database, do we have to run add migration sameMigrationName with no-build option again?

**Comment by mvanput** [comment]
@chimepalden if you add a migration with EF Core with the `--no-build`` option and then update the database you can add the `--no-build` option again. There is no need for a run add migration again.

**Comment by chimepalden** [comment]
@mvput i just ran update database command but build failed.

**Comment by chimepalden** [comment]
how do i build after no-build migration?

**Comment by mvanput** [comment]
@chimepalden what are you trying to achieve? And can you share some code and error stack?

**Comment by chimepalden** [comment]
![Screenshot (745)](https://user-images.githubusercontent.com/10587752/103925050-f0f0a380-50e4-11eb-869a-aafc9bd359cf.png)
@mvput i got this.

**Comment by chimepalden** [comment]
@mvput just wanted to create a table in database.

**Comment by mvanput** [comment]
@chimepalden this looks like an build error of the project. Build the project to see what's going on. Btw this repo is an extension for using ef core commands with cake. For using dotnet core cli please go the original repo.

**Comment by chimepalden** [comment]
@mvput ok thanks for help
