### ISSUE TITLE
Tools doesn't support List migration functionality

### ISSUE THREAD

**Issue by nick5454** [cake-contrib/Cake.DotNetCoreEf#46]
I need to get a list of all migrations to determine which migration to apply within a Release pipeline. This will allow me to build individual script to avoid schema errors.

## Expected Behavior
The ef tool was changed to return a json list of all migrations. This is needed when multiple environments in a pipeline may have different migrations.

## Current Behavior
This functionality does not exist

## Possible Solution
Add the list method call and return a string of json

## Steps to Reproduce (for bugs)
This is not a bug

## Context
in Azure Pipelines I do not if how many migrations have been applied to multiple environments. Using a full script that has multiple schema changes will cause the Azure Sql Deploy Task to fail. This allows the pipeline to get a list of migrations. The intent is to build all migrations as single files and zip them to the Release Pipeline. Each environment can determine if a migration should be applied.

## Your Environment
No bug

* Addin version used: 0.10.0
* Cake Version used: Cake.CoreCLR 0.34.0
* Operating System: Windows Azure Hosted

**Comment by nick5454** [comment]
@mvput I have attached a PR for this issue. It's sort of an urgent need.

**Comment by mvanput** [comment]
@nick5454 merged the PR, thanks for your contrib!
